export enum UltimateEntityRelationTypes {
  ONE_TO_MANY_RELATION_SELECT = "ONE_TO_MANY_RELATION_SELECT",
  MANY_TO_ONE_RELATION_SELECT = "MANY_TO_ONE_RELATION_SELECT",
  MANY_TO_MANY_RELATION_SELECT = "MANY_TO_MANY_RELATION_SELECT",
  UNKNOWN = "UNKNOWN",
}
