export enum UltimateEntityFieldTypes {
  STRING = "STRING",
  TEXT = "TEXT",
  BOOLEAN = "BOOLEAN",
  IMAGE = "IMAGE",
  SELECT = "SELECT",
  ONE_TO_MANY_RELATION_SELECT = "ONE_TO_MANY_RELATION_SELECT",
  UNKNOWN = "UNKNOWN",
  //
  // STRING_ARRAY = "STRING_ARRAY",
  // DATE = "DATE",
  // COLOR_PICKER = "COLOR_PICKER",
  // TIME = "TIME",
  // DATE_AND_TIME = "DATE_AND_TIME",
}
