export enum UltimateEntityFieldTypes {
  STRING = "STRING",
  TEXT = "TEXT",
  BOOLEAN = "BOOLEAN",
  IMAGE = "IMAGE",
  SELECT = "SELECT",
  UNKNOWN = "UNKNOWN",
  STRING_ARRAY = "STRING_ARRAY",
  DATE = "DATE",
  MARKDOWN = "MARKDOWN",
  COLOR = "COLOR",
  METADATA = "METADATA",
}
